site_name: Paper

theme:
  name: material
  features:
    - navigation.expand

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - def_list

plugins:
  - glightbox
